package invincible.privacy.joinstr.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF000000)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF262626)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF222222)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF434343)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF000000)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF262626)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFF4E0002)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFF8C0009)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFF9F9F9)
val onBackgroundLight = Color(0xFF1B1B1B)
val surfaceLight = Color(0xFFF9F9F9)
val onSurfaceLight = Color(0xFF000000)
val surfaceVariantLight = Color(0xFFEBE0E1)
val onSurfaceVariantLight = Color(0xFF282224)
val outlineLight = Color(0xFF484142)
val outlineVariantLight = Color(0xFF484142)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303030)
val inverseOnSurfaceLight = Color(0xFFFFFFFF)
val inversePrimaryLight = Color(0xFFECECEC)
val surfaceDimLight = Color(0xFFDADADA)
val surfaceBrightLight = Color(0xFFF9F9F9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3F3)
val surfaceContainerLight = Color(0xFFEEEEEE)
val surfaceContainerHighLight = Color(0xFFE8E8E8)
val surfaceContainerHighestLight = Color(0xFFE2E2E2)

val primaryDark = Color(0xFFFBFBFB)
val onPrimaryDark = Color(0xFF000000)
val primaryContainerDark = Color(0xFFCBCBCB)
val onPrimaryContainerDark = Color(0xFF000000)
val secondaryDark = Color(0xFFFBFBFB)
val onSecondaryDark = Color(0xFF000000)
val secondaryContainerDark = Color(0xFFCBCBCB)
val onSecondaryContainerDark = Color(0xFF000000)
val tertiaryDark = Color(0xFFFBFBFB)
val onTertiaryDark = Color(0xFF000000)
val tertiaryContainerDark = Color(0xFFCBCBCB)
val onTertiaryContainerDark = Color(0xFF000000)
val errorDark = Color(0xFFFFF9F9)
val onErrorDark = Color(0xFF000000)
val errorContainerDark = Color(0xFFFFBAB1)
val onErrorContainerDark = Color(0xFF000000)
val backgroundDark = Color(0xFF131313)
val onBackgroundDark = Color(0xFFE2E2E2)
val surfaceDark = Color(0xFF131313)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFF4C4546)
val onSurfaceVariantDark = Color(0xFFFFF9F9)
val outlineDark = Color(0xFFD3C8C9)
val outlineVariantDark = Color(0xFFD3C8C9)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E2)
val inverseOnSurfaceDark = Color(0xFF000000)
val inversePrimaryDark = Color(0xFF2A2A2A)
val surfaceDimDark = Color(0xFF131313)
val surfaceBrightDark = Color(0xFF393939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1B1B1B)
val surfaceContainerDark = Color(0xFF1F1F1F)
val surfaceContainerHighDark = Color(0xFF2A2A2A)
val surfaceContainerHighestDark = Color(0xFF353535)


// custom
val lightBlue = Color(0xFF2f88ff)

val greenDark = Color(0xFF4CAF50)
val yellowDark = Color(0xFFFFEB3B)
val redDark = Color(0xFFF44336)

val greenLight = Color(0xFF2E7D32)
val orangeLight = Color(0xFFFFB254)
val redLight = Color(0xFFD32F2F)